### PR TITLE
Set default token for simpler setup

### PR DESCRIPTION
**Pull request by alerque**
99 times out of 100 people won't need anything other than the default token already available in scope, defaulting to it saves everybody YAML setup mess.

### CODE REVIEW

**Comment by softprops** [comment]
Do actions inherit this env variable without explicitly declaring it? If so I'm good to merge this

**Comment by alerque** [comment]
@softprops It isn't an ENV variable. The system you were using is an ENV variable, and no those to not propagate without explicitly declaring them to be passed to an Action. What I'm doing here combines two other things: input fields which can have default values with context scoped variables, which I believe are available by default in the scope used here.

I copied this arrangement from another Action that I saw using it and found it convenient, but I guess it does bear testing out to make sure there wasn't some other kind of scope magic or authorization that I missed.

**Comment by alerque** [comment]
Here is an example on an Action that uses this arrangement: https://github.com/peter-evans/create-pull-request/blob/master/action.yml#L4-L6

**Comment by alerque** [comment]
@softprops I just fixed the merge conflicts, but it looks like the handling of `process.env.GITHUB_REPOSITORY` vs. `getInput('repostiory')` is all scrambled. It looks like it was partially implemented as an input, and now it is regressed to being only an env var. Is there some reason this can't be an optional input with a normal default value? I don't see the advantage of using an env variable here and the fallback mechanism for two env vars makes it even more confusing.

**Comment by yin1999** [comment]
I think this is a better way to get access token.
This method is also used by the [official action](https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/action.yml#L12-L24)

When using `inputs` to get the `access token`, it's default to `${{ github.token }}`

official example [here](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token)

**Comment by softprops** [comment]
The repository input was likely an effect of https://github.com/softprops/action-gh-release/pull/61

**Comment by alerque** [comment]
Yes that's where it should have come from, but it does not seem to have been implemented properly. If it was, the current documentation is surely wrong. In 94651eb the documentation was updated to reflect something different than how it should have been implemented, and honestly I can't quite make out whether it ever worked the way it was supposed to or why the documentation was changed.

Where do the `env.INPUT_*` values even get set? The GitHub Actions API for this should be `getInput()` or some such, but don't see where that's being used. I see the `@actions/core` and `@actions/github` libraries but neither of those document this kind of config handling.

**Comment by softprops** [comment]
going to cut a release with current changes in then merge this into the following.

**Pull request merged**
