### PR TITLE
Support auto generating release notes

### LINKED ISSUE #167: integrate with the new Github release notes generator
Github has recently added this button:
image

which basically just calls the github API like this:
```
Request URL: https://github.com/capaj/decapi/releases/notes?commitish=0.9.5&tag_name=0.9.5
Request Method: GET
```

and it gets back a changelog.

Would be worth making this the default way to get the changelog when it is not supplied.

### LINKED ISSUE #173: Add option to Automatically generate changelog notes
If you can automatically generate a changelog, a thumbs up

### LINKED ISSUE #176: Use automatically generated release notes from GitHub
GitHub now supports [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). As soon as you specify the version number on the GitHub's Releases page, you will get a button to generate release notes (see screenshot). 

Clicking the "Auto-generate release notes" button is still a manual process. I was wondering if this can be coupled with the `softprops/action-gh-release` workflow? 

Ideally, I would like to set up a GitHub workflow which creates a release on GitHub as soon as I tag my code. This release then should have the automatically generated release notes attached.

**Screenshot:**

image

### PR DESCRIPTION
**Pull request by xt0rted**
I'm not sure if anything else is needed to support this setting, but the change looks to match prior PRs. I used trailing commas in this update but I can remove those if you don't want them.

API Docs: https://docs.github.com/en/rest/reference/repos#create-a-release (`generate_release_notes`)

Closes #167
Closes #173
Closes #176

### CODE REVIEW

**Comment by seandstewart** [comment]
:+1: to this - I'm looking to automate a bit more of my release workflows and this would be an excellent addition.

**Review by softprops — APPROVED** [review]
This looks good. Were you able to run this branch in a workflow to verify it works?

**Comment by xt0rted** [comment]
I didn't verify the change but I can later today.

**Comment by xt0rted** [comment]
Just did a couple releases in a test repo and the change looks to work. This is the workflow used:

```yml
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: xt0rted/action-gh-release@testing
        with:
          generate_release_notes: true
```

The release created:

image

I removed the trailing commas, not sure how I missed the prettier setup for that, and added the setting to the readme.

**Comment by bennycode** [comment]
@xt0rted, I also tried your `action-gh-release@testing` and it worked like a charm. ✨ Result: https://github.com/bennycode/trading-signals/releases/tag/v2.4.1 👌

**Comment by bennycode** [comment]
@softprops thanks for merging this. Can you create a new tag & release version of your action so I can pin that in my GitHub workflow?

**Comment by bennycode** [comment]
@softprops & @xt0rted is something missing from the merged PR? I added this to my GitHub workflow:

```
      - name: Release
        uses: softprops/action-gh-release@0465cdad11d833cabb6414f885edd2ccdfda4b96
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
```

Unfortunately, it created a release with empty release notes: https://github.com/bennycode/trading-signals/releases/tag/v2.5.0

With `xt0rted/action-gh-release@testing` it was working (see [here](https://github.com/bennycode/trading-signals/releases/tag/v2.4.1)) but I can't use this action anymore because it got deleted.

**Comment by softprops** [comment]
I'll publish this weekend

**Comment by softprops** [comment]
ok. should be set here

**Comment by mikeage** [comment]
This is a bit old, but an excellent contribution. Any chance of adding an option to set the previous release? Currently, it generates to the last release created, which is a sensible default, but I'd like to differentiate between two cases:

1. Create a pre-release -- in this case, the changelog should be based on the last release of any type
2. Create a regular release -- in this case, the change should be based on the difference from the last full release (i.e., last release that's not marked as pre-release).

I'm currently creating the body for the changelog manually, but I'd like to move to letting the action trigger github's automatic generation; this is the only thing missing for me.

**Pull request merged**
