### PR TITLE
Support deleting existing releases

### PR DESCRIPTION
**Pull request by ncfavier**
Extracted from #181

Tests pass, tested [in situ](https://github.com/ncfavier/config/runs/4418208493?check_suite_focus=true#step:9:1)

### CODE REVIEW

**Comment by softprops** [comment]
Can you walk me through the usecase of deleting a release be updating an existing release?

**Comment by ncfavier** [comment]
I'm kind of abusing the release system by keeping a single release and uploading an asset to it every time it gets rebuilt. Deleting it is useful to update the last modification date.

**Comment by ncfavier** [comment]
Looks like other people have a use for this. Please consider merging.

**Comment by duskmoon314** [comment]
Will this be merged? It seems useful when keeping a pre-release of the latest commit.

**Comment by realnc** [comment]
> Can you walk me through the usecase of deleting a release be updating an existing release?

https://github.com/probonopd/linuxdeployqt/releases

In CI, we can just:

```
wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
```

The `continuous` release tag always points to the latest build.

**Comment by slashtechno** [comment]
Is there an ETA as to when this will be merged?

**Comment by ncfavier** [comment]
Following https://github.com/softprops/action-gh-release/pull/266#issuecomment-1297136024 I have switched to using the GitHub CLI tool, so I am no longer interested in this feature.

**Pull request closed without merging**
