### PR TITLE
Fix missing update release body

### LINKED ISSUE #362: The body of a release is overwritten with the content of `body_path` or `body`
## Prelude

Hi,

I'm using this action to create a release. 

I provide a body to that release that contain the check sum of the released artifacts.

Those check sum aren't stable since we don't have reproducible build at the moment.

## Using `body_path`

That body come from a generated file that is provided within the field `body_path`.

It appends that I run the workflow twice and the body wasn't updated of the second run.

It's currently configured like so:

```yaml
      - name: Create release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
        with:
          draft: true
          body_path: release-summary.md
          name: Release v${{ needs.version.outputs.full }}
          tag_name: v${{ needs.version.outputs.full }}
          files: foobar.md
          fail_on_unmatched_files: true
          generate_release_notes: false
        timeout-minutes: 5
```

## Using `body`

I've also tried to use `body` instead of `body_path` with no luck, the body of the release is still not updated.

```yaml
      - name: Create release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
        with:
          draft: true
          body: ${{ steps.summary.outputs.output }} 
          name: Release v${{ needs.version.outputs.full }}
          tag_name: v${{ needs.version.outputs.full }}
          files: foobar.md
          fail_on_unmatched_files: true
          generate_release_notes: false
        timeout-minutes: 5
```

## What I'm expected

I would expect that the body is updated.

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
This PR correct the bug I was getting in #362.

This problem was that draft aren't updated once created.

I've rewrote how the function `release` handle a draft and a non-draft release to be processed in the same way.

Closes #362

### CODE REVIEW

**Comment by mitchelbaker-cisa** [comment]
Bumping this PR since I'm facing the same issue. At times the workflow I'm generating will create a new body which I want to overwrite what's contained in a draft release. Currently the draft stays the same.

**Comment by FirelightFlagboy** [comment]
Hello @softprops, I'm pinging you in hope that you could review this PR :)

**Comment by chenrui333** [comment]
@FirelightFlagboy can you fix the merge conflicts? Thanks!

**Comment by chenrui333** [comment]
@FirelightFlagboy thanks for helping out.

**Pull request merged**
