### PR TITLE
Fix deprecated

### PR DESCRIPTION
**Pull request by sameer0583**

### CODE REVIEW

**Comment by JiPaix** [comment]
this would close #268, #264, #265, #263, #250, #249.

**Comment by rix1337** [comment]
@softprops this seems to be a relevant fix, but does not remove the set-output deprecation notice

**Comment by rix1337** [comment]
For those of you looking for an up2date alternative, just go and use https://github.com/ncipollo/release-action

**Comment by koplo199** [comment]
You need to regenerate the `package-lock.json` file _and_ the `dist` directory, as is this PR won't do anything. It can't even pass the CI.

**Comment by koplo199** [comment]
I've done it (among other things) in #275.

**Comment by sameer0583** [comment]
> You need to regenerate the `package-lock.json` file _and_ the `dist` directory, as is this PR won't do anything. It can't even pass the CI.

Yea, you need to do what is in https://github.com/softprops/action-gh-release/blob/master/.github/workflows/main.yml

However, that action in itself is broken as it should run `npm install` before.  Those changes are not pertinent to the actual fixes this addresses and is more a general fix

**Comment by sameer0583** [comment]
I was able to regenerate all the files in my forked repo, use it in another workflow with no dependency issues

**Comment by softprops** [comment]
hi folks this should be fixed now with https://github.com/softprops/action-gh-release/pull/275

**Pull request closed without merging**
