### PR TITLE
Add tag_name option

### PR DESCRIPTION
**Pull request by k-takata**
Allow setting tag name like [actions/create-release](https://github.com/actions/create-release).

I want to create a tag in a workflow and create a release for that tag. In that case, `GITHUB_REF` doesn't point to the tag.

### CODE REVIEW

**Comment by softprops** [comment]
neat. This may actually solve for some of the related open issues in this repo. I should be able to publish a new release before the end of this weekend. I'll ping you in this thread when I do

**Comment by gabriel-kohen-jdas** [comment]
I've just tried using it and for some reason it returns an error:
image

**Comment by k-takata** [comment]
This is not included in `@v0.1.5`. You need to use `@master` for now.

**Comment by dvc94ch** [comment]
I'm getting this error:
```sh
Run softprops/action-gh-release@master
⚠️ Unexpected error fetching GitHub release for tag refs/tags/f-f001ea29f1b9664d928acfddbbd9c76a942e2238: HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
##[error]Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
##[error]Node run failed with exit code 1
```
The situation I have is that I'm building multiple releases [stable, beta, dev] in a job, since the repo only contains build scripts. I suspect that you can only update the latest release. Has someone encountered this before?

**Comment by daltskin** [comment]
@dvc94ch I had this today:

##[error]Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

(I'm also using matrixes) - but on when I ran it again it worked...

**Comment by dvc94ch** [comment]
I don't remember the solution, but I somehow got it to work or worked around it

**Pull request merged**
