### PR TITLE
Add release id to outputs

### PR DESCRIPTION
**Pull request by loicalbertin**
This allows to retrieve the release ID as an output for use in next steps of a workflow

### CODE REVIEW

**Comment by gmazzap** [comment]
Hi here, I just needed exactly this today.

Is there anything I can do to help in move this forward?

**Comment by loicalbertin** [comment]
I can have a look on resolving conflicts if there is any chance to see this merged.
WDYT @softprops?

**Comment by Frederick888** [comment]
Much appreciated for this PR. I've got a Draft Release -> Parallel Build & Upload -> Publish Release workflow and I need this ID for https://github.com/eregon/publish-release (the built-in `files` doesn't work for me since I'd like to see artifacts even not all builds are successful).

@softprops Any chance we can move forward with this? Thanks.

**Review by softprops — APPROVED** [review]

**Comment by softprops** [comment]
Sorry for the delay. it seems like some merge conflicts still exist on this one. I’d be happy to merge after those get addressed

**Comment by loicalbertin** [comment]
Hi @softprops,

No problem. Merge conflicts are solved now.

**Comment by loicalbertin** [comment]
Hi @softprops, 

Thanks for merging this PR! 👍

**Pull request merged**
