### PR TITLE
Follow symbolic links

### LINKED ISSUE #182: symlinks to files are not released
The result of the `with.files` glob is checked against [isFile()](https://github.com/softprops/action-gh-release/blob/0465cdad11d833cabb6414f885edd2ccdfda4b96/src/util.ts#L77), which doesn't follow symlinks - it really should!

### PR DESCRIPTION
**Pull request by ncfavier**
Allow uploading files from symbolic links.

Closes #182

### CODE REVIEW

**Comment by softprops** [comment]
This looks good to me. Can you confirm this change works with regular files as well?

**Comment by ncfavier** [comment]
It does!

**Comment by softprops** [comment]
awesome.

**Comment by softprops** [comment]
I'll pull this into a release this weekend. Thanks for fixing this!

**Comment by ncfavier** [comment]
Thanks. I'd be grateful if you could also merge #185 and #181.

**Pull request merged**
