### PR TITLE
feature: preserve upload order

### PR DESCRIPTION
**Pull request by richarddd**
Fixes: https://github.com/softprops/action-gh-release/issues/44

### CODE REVIEW

**Comment by richarddd** [comment]
@chenrui333 sorry for the bump but is this something you can take a look at please? 🙂

**Review by chenrui333 — APPROVED** [review]
lgtm, can you add a test for it?

**Comment by chenrui333** [comment]
```
Error: [tsl] ERROR in /home/runner/work/action-gh-release/action-gh-release/src/main.ts(91,18)
      TS2339: Property 'preserve_order' does not exist on type 'Config'.
```

**Comment by richarddd** [comment]
Thanks. Tests should pass now!

**Comment by richarddd** [comment]
@chenrui333 can we merge this please?

**Comment by richarddd** [comment]
@chenrui333 @kbakdev would be great if we can merge and release :)

**Comment by chenrui333** [comment]
@richarddd sorry about the delay, and thanks for your first contribution!! 🙏 ❤️

**Pull request merged**
