### PR TITLE
Fix deprecation warning

### LINKED ISSUE #265: Update the set-output command (deprecation warning)
### What would you like to be added?

```
      - name: Create release
        uses: softprops/action-gh-release@v1
```

When using this Action in a Workflow, GitHub displays a warning:

`The 'set-output' command is deprecated and will be disabled soon.`

So the ```set-output``` command should be updated... so that no warnings of deprecations are being displayed.

### Why is this needed?

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by alexevanczuk**
# Summary

Fixes #265 to prevent deprecation warnings in user consoles:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The recommended approach in the blog post is to upgrade `@actions/core` to `1.10.0`.

When I ran `npm` install, I got this, 
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
(################⠂⠂) ⠧ idealTree:inflate:node_modules/assert-plus: sill inflate node_modules/assert-plus
```

I believe this is the cause of the large change in `package-lock.json`.

I tested this locally (by pointing another project at my fork) and verified it removes the deprecation warning.

# Commits
- Bump @actions/core to 1.10.0
- npm install

### CODE REVIEW

**Comment by alexevanczuk** [comment]
@softprops Let me know if you'd have time to review and merge this change. If not, I'll close this PR.

**Comment by jepler** [comment]
Hi! At @adafruit we use this action. Please let us know if we can help get this PR accepted.

**Comment by alexevanczuk** [comment]
Hey folks I'm going to close this out for now. We can always reopen it up and merge it.

In the meantime, I'll recommend two alternative approaches:
- In some issues/PRs that have referenced this one, folks found https://github.com/ncipollo/release-action, which appears to be highly used, frequently maintained, and ranks high on the GitHub marketplace.
- I'd highly recommend just using the vanilla GH CLI client, which [is fully supported](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows). You can find an example of this in use for creating releases during CD here https://github.com/rubyatscale/use_packwerk/blob/main/.github/workflows/cd.yml, and you can see a more extended blog post I wrote on CI/CD [here](https://medium.com/gradual/a-start-to-finish-walkthrough-on-creating-a-ruby-gem-with-ci-and-cd-a2b705047087).

**Comment by DavidWiseman** [comment]
> Hey folks I'm going to close this out for now. We can always reopen it up and merge it.
> 
> In the meantime, I'll recommend two alternative approaches:
> 
> * In some issues/PRs that have referenced this one, folks found https://github.com/ncipollo/release-action, which appears to be highly used, frequently maintained, and ranks high on the GitHub marketplace.
> * I'd highly recommend just using the vanilla GH CLI client, which [is fully supported](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows). You can find an example of this in use for creating releases during CD here https://github.com/rubyatscale/use_packwerk/blob/main/.github/workflows/cd.yml, and you can see a more extended blog post I wrote on CI/CD [here](https://medium.com/gradual/a-start-to-finish-walkthrough-on-creating-a-ruby-gem-with-ci-and-cd-a2b705047087).

Thanks.  I've decided to replace with GH CLI.

**Comment by jepler** [comment]
@tekktrik we should investigate the above options for library actions

**Pull request closed without merging**
