### PR TITLE
Update node version to node20

### LINKED ISSUE #404: Replace Node.js 16 with Node.js 20
GitHub actions is planning to [deprecate Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The file existence action is still using Node 16. We are getting this warning that the file exists action should be updated to Node 20

### PR DESCRIPTION
**Pull request by timheuer**
Fixes #404 updating the action to use `node20`

### CODE REVIEW

**Comment by s1204IT** [comment]
@softprops 
Now that the node16 warning has started appearing, this should be addressed as soon as possible.

**Comment by peabee** [comment]
@softprops - would be great if this update could be actioned - thanks.

**Comment by jamesbuddrige** [comment]
+1 For upgrading this

**Comment by lxiaya** [comment]
update - thanks.

**Comment by steven-prybylynskyi** [comment]
@softprops merge it please

**Comment by s1204IT** [comment]
Now all we have to do is retagging the v1 tag!

**Comment by peabee** [comment]
> Now all we have to do is retagging the v1 tag!

Needs to be a new release...............??

**Comment by s1204IT** [comment]
> > Now all we have to do is retagging the v1 tag!
> 
> Needs to be a new release...............??

Well, it's true that `v2` is fine, but honestly it's easier to stay with `v1` xD
This is ultimately up to the developer, but either way you should tag and release early.

**Comment by ivanlemeshev** [comment]
Please create a new release. We need this action to work.

**Comment by timheuer** [comment]
As an alternate everyone you can modify your action to use a commit hash. 

So you can use
`softprops/actuon-gh-release@ 4634c16e79c963813287e889244c50009e7f0981`

this will use the merged node20 commit.

**Comment by akinomyoga** [comment]
@softprops Is there a plan to tag a new release? I'm wondering when I should update the GitHub actions in my projects. If the new tag will be released soon, I'd like wait for it to avoid cluttering the history with a temporary change. If the new tag will not appear, I probably need to use the (temporary) solution suggested in https://github.com/softprops/action-gh-release/pull/406#issuecomment-1934635958.

**Comment by barunprasad** [comment]
We're currently awaiting compatibility of the latest tag with Node.js version 20. From my perspective, it would be advisable to consider a major version increment in light of this.

**Comment by trackleft** [comment]
@softprops hasn't done anything in github for a couple of weeks, hope he's OK 
image

**Comment by softprops** [comment]
Sorry folks hope to get to this soon. I'm through a layoff event in my life and trying to prioritize getting certain things in order.

**Comment by akinomyoga** [comment]
Oh, I'm sorry to hear that. I can wait, so please take your time for your life. Needless to say, that's more important than GitHub Action. Don't worry, there are currently just warnings, and nothing is broken.

**Comment by mikeage** [comment]
I admit, I chuckled at the fact that of all the repos to be missing a release, it was this one ;-)

But seriously, I hope everything is ok and you're doing well. Work stress is never fun.

**Comment by tychobrailleur** [comment]
> Sorry folks hope to get to this soon. I'm through a layoff event in my life and trying to prioritize getting certain things in order.

Virtual hug 🫂  Take care of yourself.

**Comment by dirkhh** [comment]
layoffs suck. life comes first.
all the best

**Comment by softprops** [comment]
thanks for the support folks

sorry for the huge delay. This should now be fixed. 

You should now use `softprops/action-gh-release@v2`. 

I've validated this in a test run repo [here](https://github.com/softprops/action-gh-releases-test/actions/runs/8208797559/job/22452960972) 

PS. THANK YOU everyone for your emotional support. I really need(ed) it.

**Pull request merged**
