### PR TITLE
Support custom target_commitish value

### PR DESCRIPTION
**Pull request by ThomasPiskol**
This PR introduces a new input `target_commitish`. 

By using this input you can provide a custom value for the commit which is used by the GitHub release. 
If this value is not provided, GitHub will use the default branch, see the [API documentation](https://docs.github.com/en/rest/reference/repos#create-a-release).

Now it's possible to provide a specific commit if you create a release without a tag:

```yaml
    - name: Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        target_commitish: ${{github.sha}}
        ...
```

I've update the existing tests and added a new test for checking the parsing of the configuration.

### CODE REVIEW

**Comment by garronej** [comment]
I wish it be merged

**Comment by c24w** [comment]
Just ran into this problem after naively assuming it would respect the contextual commitish (e.g. `GITHUB_SHA`).  Is there something preventing this being merged?

**Comment by ThomasPiskol** [comment]
I've integrated the latest changes from upstream. 
@softprops is there anything else what I need to do?

**Comment by softprops** [comment]
Looks good. Thanks for 
 contributing!

**Comment by c24w** [comment]
Please can you release this, too?  We're keen to get this change into our projects, rather than looking for an alternative.

**Comment by manorit2001** [comment]
@softprops any tentative date for the new release?

**Comment by AlbertCintas** [comment]
Hello! Also would love for the change to be released.

**Comment by scooper91** [comment]
Hi @softprops! It looks like this still isn't released.  Please can you release it so we can start using the feature? Thanks!

**Pull request merged**
