### PR TITLE
Fix updating draft releases

### PR DESCRIPTION
**Pull request by vadz**
Sorry again, after opening #254 and then closing it because I've noticed the already existing #245, I'm finally opening this one because, after looking at #245, I believe this one is slightly better because it correctly uses `createRelease()` if a draft release does _not_ exist, rather than using `updateRelease()` even in this case. Even if the latter works too, using `createRelease()` looks preferable and, at the very least, results in the expected message in the logs.

I've also changed the way we're looking for the existing draft release in this one because using the (empty) tag doesn't seem to be the right thing to do neither.

Please note that although it looks like there are many changes here, using `git diff -w --color-moved --color-words` shows that most of them are actually due to just moving the code around.

### CODE REVIEW

**Comment by vadz** [comment]
I've rebased the original branch on the latest master to avoid conflicts due to formatting changes.

Please let me know if you have any questions or comments about this PR, it would be really nice to see it merged.

**Comment by chenrui333** [comment]
@vadz  can you fix the merge conflicts? Thanks!

**Comment by vadz** [comment]
There are too many conflicts with fb2d031 (Fix missing update release body (#365), 2024-07-17) and I think that PR fixed the same problem, albeit in a somewhat different way. I haven't tested if it's really fixed for me yet however, but if there are no known problems with the other PR, this one can be closed.

**Comment by chenrui333** [comment]
@vadz sounds great, feel free to throw another PR. Thanks!

**Pull request closed without merging**
