### PR TITLE
Add support for make_latest property

### LINKED ISSUE #297: add support for make_latest parameter
GH releases have a "make_latest' parameter as detailed in https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release that is not currently supported

### PR DESCRIPTION
**Pull request by samueljseay**
Closes #297 

This PR supports the `make_latest` property of the [releases REST API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release).

I've tested this on my fork and it works well for me. I've kept the behaviour with previous versions by defaulting to true for this property.

I also:

* updated a dependency via `npm audit fix` to fix a high risk npm security flag
* updated tests
* updated documentation

Please note: `make_latest` is oddly a string which is why parseConfig returns a string for this property. See [the docs](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release).

### CODE REVIEW

**Comment by softprops** [comment]
Thanks!

There's some nuance in the docs that give me pause for the default though

> Drafts and prereleases cannot be set as latest. 

Does this mean those creating drafts and prereleases would start getting errors with this actions new default?

> Defaults to true for newly published releases. legacy specifies that the latest release should be determined based on the release creation date and higher semantic version.

I'm wondering if legacy is the better default for backwards compat or event better leaving it undefined as a default unless a user specifies it explicitly to guarantees compatibility with current behavior

**Comment by samueljseay** [comment]
Leaving undefined sounds probably better I agree. I'll add a change for that.

**Comment by samueljseay** [comment]
@softprops I've adjusted the behaviour to default to `undefined`.

**Comment by jackalcooper** [comment]
Hi, will this PR be merged?

**Comment by DameonSmith** [comment]
Would also like to see this feature.

**Comment by damian3031** [comment]
I'm also interested in this feature

**Comment by DariuszPorowski** [comment]
@softprops any updates on this? :)

**Comment by koehlecn** [comment]
@softprops Please, can your merge this PR? That would be great! Thank you!

**Comment by leon1995** [comment]
any news on this?

**Comment by kdmiltner** [comment]
Could support to update an existing tag with make_latest be added? Or would this would to set an existing tag to the latest? https://github.com/softprops/action-gh-release/issues/385

**Comment by theo-issarni-wmx** [comment]
Any news on this ? That would be great !

**Comment by softprops** [comment]
@samueljseay thanks for the pull and sorry for the delay

**Comment by softprops** [comment]
this should be available in the new v2 tag

**Pull request merged**
