### PR TITLE
pick one body

### PR DESCRIPTION
**Pull request by softprops**
when building a body, don't repeat content that might already exist.

### CODE REVIEW

**Comment by 0x90d** [comment]
@softprops Is there a reason why you don't have merged it yet?

**Comment by softprops** [comment]
I wanted to make sure I'd given it test run. first would you be able to give this a spin before merging to master. 

would you be able to give this a spin. you should be able to reference it by branch `pick-one-body`

**Comment by 0x90d** [comment]
@softprops Sorry for the late reply, I didn't get any notification although I've subscribed. How can I reference to this branch, do I need to change my workflow line from: `uses: softprops/action-gh-release@v1` to `uses: softprops/action-gh-release@pick-one-body` ?

**Comment by softprops** [comment]
that's correct

**Comment by 0x90d** [comment]
@softprops I've tested it and it works fine

**Comment by softprops** [comment]
thanks for testing! Ill merge and release the changes this weekend. Ill post back here for visibility

**Comment by softprops** [comment]
changes should but pushed to v1 tag now

**Comment by abcfy2** [comment]
But how to repeat? I need this feature for matrix build and output for different build info.

**Comment by softprops** [comment]
I think we're going to need a customization input flag for that. I'd like for defaults to work for the common cases if there's demand we can add a hook for customization

**Comment by abcfy2** [comment]
> I think we're going to need a customization input flag for that. I'd like for defaults to work for the common cases if there's demand we can add a hook for customization

Any update ? Thanks.

**Pull request merged**
